apiVersion: v1
kind: Service
metadata:
  name: svc1
  labels:
    app: app-v1
spec:
  selector:
    app: app-v1
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32001
      protocol: TCP
  type: NodePort
